//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX__WS_WEBPG_SECTION_HISTORY
    {
        public decimal SECTION_ID { get; set; }
        public decimal WS_APP_ID { get; set; }
        public decimal WEBPAGE_ID { get; set; }
        public Nullable<decimal> OLD_DISPLAY_SEQUENCE { get; set; }
        public Nullable<decimal> NEW_DISPLAY_SEQUENCE { get; set; }
        public string OLD_TITLE { get; set; }
        public string NEW_TITLE { get; set; }
        public string OLD_CONTENT { get; set; }
        public string NEW_CONTENT { get; set; }
        public string APPLICATION_USER_ID { get; set; }
        public System.DateTime CHANGE_DATE { get; set; }
    }
}
