//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX_TEAM_DEV_FILES
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ROW_VERSION_NUMBER { get; set; }
        public decimal COMPONENT_ID { get; set; }
        public string COMPONENT_TYPE { get; set; }
        public string FILENAME { get; set; }
        public string FILE_MIMETYPE { get; set; }
        public string FILE_CHARSET { get; set; }
        public byte[] FILE_BLOB { get; set; }
        public string FILE_COMMENTS { get; set; }
        public string TAGS { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
