//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX__WS_LINKS
    {
        public decimal ID { get; set; }
        public decimal WS_APP_ID { get; set; }
        public Nullable<decimal> DATA_GRID_ID { get; set; }
        public Nullable<decimal> WEBPAGE_ID { get; set; }
        public string COMPONENT_LEVEL { get; set; }
        public string TAGS { get; set; }
        public string SHOW_ON_HOMEPAGE { get; set; }
        public string LINK_NAME { get; set; }
        public string URL { get; set; }
        public string LINK_DESCRIPTION { get; set; }
        public Nullable<decimal> DISPLAY_SEQUENCE { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_ON { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual APEX__WS_ROWS APEX__WS_ROWS { get; set; }
    }
}
