//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEX__WS_HISTORY
    {
        public decimal ROW_ID { get; set; }
        public decimal WS_APP_ID { get; set; }
        public decimal DATA_GRID_ID { get; set; }
        public string COLUMN_NAME { get; set; }
        public string OLD_VALUE { get; set; }
        public string NEW_VALUE { get; set; }
        public string APPLICATION_USER_ID { get; set; }
        public Nullable<System.DateTime> CHANGE_DATE { get; set; }
    }
}
