//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BackendDBEntities : DbContext
    {
        public BackendDBEntities()
            : base("name=BackendDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APEX__ACL> APEX__ACL { get; set; }
        public virtual DbSet<APEX__WS_FILES> APEX__WS_FILES { get; set; }
        public virtual DbSet<APEX__WS_LINKS> APEX__WS_LINKS { get; set; }
        public virtual DbSet<APEX__WS_NOTES> APEX__WS_NOTES { get; set; }
        public virtual DbSet<APEX__WS_ROWS> APEX__WS_ROWS { get; set; }
        public virtual DbSet<APEX__WS_TAGS> APEX__WS_TAGS { get; set; }
        public virtual DbSet<APEX__WS_WEBPG_SECTIONS> APEX__WS_WEBPG_SECTIONS { get; set; }
        public virtual DbSet<APEX_TEAM_DEV_FILES> APEX_TEAM_DEV_FILES { get; set; }
        public virtual DbSet<DEMO_CONSTRAINT_LOOKUP> DEMO_CONSTRAINT_LOOKUP { get; set; }
        public virtual DbSet<DEMO_CUSTOMERS> DEMO_CUSTOMERS { get; set; }
        public virtual DbSet<DEMO_ORDER_ITEMS> DEMO_ORDER_ITEMS { get; set; }
        public virtual DbSet<DEMO_ORDERS> DEMO_ORDERS { get; set; }
        public virtual DbSet<DEMO_PRODUCT_INFO> DEMO_PRODUCT_INFO { get; set; }
        public virtual DbSet<DEMO_TAGS> DEMO_TAGS { get; set; }
        public virtual DbSet<DEMO_TAGS_SUM> DEMO_TAGS_SUM { get; set; }
        public virtual DbSet<DEMO_TAGS_TYPE_SUM> DEMO_TAGS_TYPE_SUM { get; set; }
        public virtual DbSet<DEPT> DEPT { get; set; }
        public virtual DbSet<EMP> EMP { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENT { get; set; }
        public virtual DbSet<INGREDIENT_CATEGORY> INGREDIENT_CATEGORY { get; set; }
        public virtual DbSet<PACKAGE> PACKAGE { get; set; }
        public virtual DbSet<RECIEPE> RECIEPE { get; set; }
        public virtual DbSet<RECIEPE_INGREDIENTS> RECIEPE_INGREDIENTS { get; set; }
        public virtual DbSet<RULE> RULE { get; set; }
        public virtual DbSet<RULE_CATEGORIES> RULE_CATEGORIES { get; set; }
        public virtual DbSet<SHAPE> SHAPE { get; set; }
        public virtual DbSet<APEX__WS_HISTORY> APEX__WS_HISTORY { get; set; }
        public virtual DbSet<APEX__WS_WEBPG_SECTION_HISTORY> APEX__WS_WEBPG_SECTION_HISTORY { get; set; }
    }
}
