//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO_TAGS
    {
        public decimal ID { get; set; }
        public string TAG { get; set; }
        public Nullable<decimal> CONTENT_ID { get; set; }
        public string CONTENT_TYPE { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<decimal> FRONTEND_ID { get; set; }
        public Nullable<decimal> MANUFACTURER_ID { get; set; }
    }
}
