//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO_ORDER_ITEMS
    {
        public decimal ORDER_ITEM_ID { get; set; }
        public decimal ORDER_ID { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<decimal> FRONTEND_ID { get; set; }
        public Nullable<decimal> MANUFACTURER_ID { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
    
        public virtual DEMO_ORDERS DEMO_ORDERS { get; set; }
        public virtual DEMO_PRODUCT_INFO DEMO_PRODUCT_INFO { get; set; }
    }
}
