//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGREDIENT()
        {
            this.RECIEPE_INGREDIENTS = new HashSet<RECIEPE_INGREDIENTS>();
        }
    
        public decimal ID { get; set; }
        public decimal PRICE { get; set; }
        public string FILENAME { get; set; }
        public string MIMETYPE { get; set; }
        public byte[] INGREDIENT_IMAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOCATION_TOP { get; set; }
        public string LOCATION_BOTTOM { get; set; }
        public string LOCATION_CHOC { get; set; }
        public decimal CATEGORY_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<System.DateTime> IMAGE_LAST_UPDATE { get; set; }
        public Nullable<decimal> FRONTEND_ID { get; set; }
        public Nullable<decimal> MANUFACTURER_ID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
    
        public virtual INGREDIENT_CATEGORY INGREDIENT_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIEPE_INGREDIENTS> RECIEPE_INGREDIENTS { get; set; }
    }
}
