//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAST_SYNCHED
    {
        public Nullable<System.DateTime> MANUFACTURER_LAST_SYNCHED { get; set; }
        public Nullable<System.DateTime> FRONTEND_LAST_SYNCHED { get; set; }
        public decimal ID { get; set; }
    }
}
