//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendDataHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHAPE
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string FILENAME { get; set; }
        public string MIMETYPE { get; set; }
        public byte[] SHAPE_IMAGE { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<System.DateTime> IMAGE_LAST_UPDATE { get; set; }
    
        public virtual DEMO_PRODUCT_INFO DEMO_PRODUCT_INFO { get; set; }
    }
}
